name: Frontend Build

on:
  repository_dispatch:
    types: [trigger-build]
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the frontend repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner.lowercase }}/conduit-frontend:latest
          build-args: |
            API_URL=${{ vars.API_URL }}

  trigger_deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Trigger deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: JohnTwiiX/Conduit_Container
          token: ${{ secrets.PAT }}
          event-type: trigger-deploy
          client-payload: '{"service_name": "frontend"}'